#!/usr/bin/env python3
"""Bake the dot-matrix land grid in map-dots.js.

The previous asset was generated by a gen_dots.mjs that was never committed, so
when the map needed new bounds there was no way to regenerate it and the crop
had silently become wrong: it spanned 115W-36E, which is a North Atlantic crop,
and every APAC pin fell outside the artboard. This script is committed for that
reason. Run it, commit the output, do not hand-edit map-dots.js.

    python3 tools/gen_dots.py

Source: Natural Earth 1:110m land polygons, public domain.
Fetched at generation time only. The site itself makes zero network requests.
"""

import json
import os
import sys
import urllib.request

SRC = ("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
       "master/geojson/ne_110m_land.geojson")
CACHE = os.path.join(os.path.dirname(__file__), "ne_110m_land.geojson")
OUT = os.path.join(os.path.dirname(__file__), os.pardir, "map-dots.js")

# Bounds and sampling. 4 px per degree, sampled every 0.85 deg, which is the
# density of the previous asset. Canvas falls out of the bounds exactly:
#   (145 - -10) * 4 = 620      (72 - -12) * 4 = 336
LON_MIN, LON_MAX = -10.0, 145.0
LAT_MIN, LAT_MAX = -12.0, 72.0
STEP = 0.85
SCALE = 4


def load_rings():
    if not os.path.exists(CACHE):
        sys.stderr.write("fetching %s\n" % SRC)
        with urllib.request.urlopen(SRC, timeout=60) as r:
            data = r.read()
        with open(CACHE, "wb") as f:
            f.write(data)
    with open(CACHE, "rb") as f:
        gj = json.load(f)

    polys = []          # [(outer_ring, [hole, ...], bbox), ...]
    for feat in gj["features"]:
        geom = feat["geometry"]
        parts = ([geom["coordinates"]] if geom["type"] == "Polygon"
                 else geom["coordinates"])
        for rings in parts:
            outer = [(float(x), float(y)) for x, y in rings[0]]
            holes = [[(float(x), float(y)) for x, y in h] for h in rings[1:]]
            xs = [p[0] for p in outer]
            ys = [p[1] for p in outer]
            polys.append((outer, holes, (min(xs), min(ys), max(xs), max(ys))))
    return polys


def in_ring(x, y, ring):
    """Ray casting. Ring is a closed list of (lon, lat)."""
    inside = False
    n = len(ring)
    j = n - 1
    for i in range(n):
        xi, yi = ring[i]
        xj, yj = ring[j]
        if (yi > y) != (yj > y):
            xint = (xj - xi) * (y - yi) / (yj - yi) + xi
            if x < xint:
                inside = not inside
        j = i
    return inside


def is_land(x, y, polys):
    for outer, holes, (x0, y0, x1, y1) in polys:
        if x < x0 or x > x1 or y < y0 or y > y1:
            continue                      # bbox reject, the whole speed story
        if in_ring(x, y, outer):
            if any(in_ring(x, y, h) for h in holes):
                continue                  # hole, e.g. the Caspian
            return True
    return False


def main():
    polys = load_rings()
    cols = int(round((LON_MAX - LON_MIN) / STEP))
    rows = int(round((LAT_MAX - LAT_MIN) / STEP))

    dots = []
    for r in range(rows + 1):
        lat = LAT_MAX - r * STEP
        for c in range(cols + 1):
            lon = LON_MIN + c * STEP
            if is_land(lon, lat, polys):
                dots.append(c)
                dots.append(r)

    header = (
        "/* Generated by tools/gen_dots.py from Natural Earth 1:110m land\n"
        "   polygons (public domain). Do not edit by hand: run the script.\n"
        "   Dot-matrix land grid, equirectangular, lon %g..%g, lat %g..%g,\n"
        "   step %g deg, %d px per degree. Canvas %d x %d, viewBox 0 0 %d %d.\n"
        "   Pixel transform, and the ONLY place it is written down:\n"
        "     x = %d + %d * lon      y = %d - %d * lat  */\n"
    ) % (LON_MIN, LON_MAX, LAT_MIN, LAT_MAX, STEP, SCALE,
         int((LON_MAX - LON_MIN) * SCALE), int((LAT_MAX - LAT_MIN) * SCALE),
         int((LON_MAX - LON_MIN) * SCALE), int((LAT_MAX - LAT_MIN) * SCALE),
         int(-LON_MIN * SCALE), SCALE, int(LAT_MAX * SCALE), SCALE)

    grid = ("const MAP_GRID = { lonMin: %g, lonMax: %g, latMin: %g, latMax: %g, "
            "step: %g, scale: %d, w: %d, h: %d };\n") % (
        LON_MIN, LON_MAX, LAT_MIN, LAT_MAX, STEP, SCALE,
        int((LON_MAX - LON_MIN) * SCALE), int((LAT_MAX - LAT_MIN) * SCALE))

    body = "const MAP_DOTS = [" + ",".join(str(v) for v in dots) + "];\n"

    with open(OUT, "w") as f:
        f.write(header + grid + body)

    sys.stderr.write("%d dots, grid %dx%d -> %s\n"
                     % (len(dots) // 2, cols + 1, rows + 1, os.path.abspath(OUT)))


if __name__ == "__main__":
    main()
